theme: jekyll-theme-architect

title: [Metro]
description: [Metro - Webservice toolkit]

# sidebar links url
links:
  source: sources
  download: download
  mailinglist: https://javaee.groups.io/g/metro
  #javadocs:
  docs:
    gettingstarted: doc/getting-started/index.html
    userguide: doc/user-guide/index.html
    
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

